#!/usr/bin/env python3
# Renders agents/<name>/customization.json into agents/<name>/system_prompt.txt via Jinja2.

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    from jinja2 import Environment, FileSystemLoader, TemplateError
    from jsonschema import Draft202012Validator
except ImportError:
    print(
        "Missing required packages. Run: pip install -r requirements.txt",
        file=sys.stderr,
    )
    sys.exit(1)


PROJECT_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = PROJECT_ROOT / "schemas" / "customization.schema.json"
TEMPLATES_DIR = PROJECT_ROOT / "templates" / "system_prompt"
AGENTS_DIR = PROJECT_ROOT / "agents"
SETTINGS_PATH = PROJECT_ROOT / "settings.json"
KNOWN_USE_CASES = ("sme", "sales_coach")


def fail(msg: str, code: int = 1) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(code)


def resolve_agent_name(arg_name: str | None) -> str:
    if arg_name:
        return arg_name
    if not SETTINGS_PATH.exists():
        fail(
            "No settings.json found. Run ./setup first, or use ./render --agent <name>."
        )
    try:
        settings = json.loads(SETTINGS_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        fail(f"settings.json is not valid JSON: {e}")
    name = settings.get("projectName")
    if not name:
        fail("settings.json is missing 'projectName'. Run ./setup to repair it.")
    return name


def load_customization(agent_name: str) -> dict:
    path = AGENTS_DIR / agent_name / "customization.json"
    if not path.exists():
        fail(
            f"No customization.json found at agents/{agent_name}/. "
            f"Run ./setup to create one, or copy a starter from templates/starters/."
        )
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        fail(f"agents/{agent_name}/customization.json is not valid JSON: {e}")


def validate(data: dict) -> None:
    try:
        schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail(f"Schema not found at {SCHEMA_PATH.relative_to(PROJECT_ROOT)}")
    except json.JSONDecodeError as e:
        fail(f"Schema is not valid JSON: {e}")

    validator = Draft202012Validator(schema)
    errors = sorted(validator.iter_errors(data), key=lambda e: list(e.absolute_path))
    if not errors:
        return

    lines = ["customization.json failed schema validation:"]
    for err in errors:
        path = ".".join(str(p) for p in err.absolute_path) or "<root>"
        lines.append(f"  - {path}: {err.message}")
    # Friendlier hint when persona.name is the missing required field.
    if any(
        e.validator == "required"
        and "'name'" in e.message
        and list(e.absolute_path) == ["persona"]
        for e in errors
    ):
        lines.append(
            "  hint: 'persona.name' is required at minimum. Start from a starter pack in templates/starters/."
        )
    fail("\n".join(lines))


def render_template(data: dict) -> tuple[str, str]:
    use_case = data.get("useCase")
    if use_case not in KNOWN_USE_CASES:
        fail(
            f"Unknown use case '{use_case}'. Available: {', '.join(KNOWN_USE_CASES)}"
        )

    env = Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        keep_trailing_newline=True,
        trim_blocks=False,
        lstrip_blocks=False,
    )

    template_name = f"{use_case}.j2"
    try:
        template = env.get_template(template_name)
        rendered = template.render(**data)
    except TemplateError as e:
        fail(f"Template render error in {template_name}: {e}")

    return rendered, template_name


def header_for(use_case: str, schema_version: str, agent_name: str) -> str:
    return (
        "# AUTO-GENERATED — do not edit this file directly.\n"
        f"# Edit agents/{agent_name}/customization.json instead, then run ./render.\n"
        f"# Template: {use_case}.j2 | Schema: {schema_version}\n\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Render an agent's system_prompt.txt from its customization.json."
    )
    parser.add_argument(
        "--agent",
        help="Agent name (directory under agents/). Defaults to settings.json projectName.",
        default=None,
    )
    args = parser.parse_args()

    agent_name = resolve_agent_name(args.agent)
    data = load_customization(agent_name)
    validate(data)
    body, _template_name = render_template(data)

    output = header_for(data["useCase"], data["schemaVersion"], agent_name) + body
    out_path = AGENTS_DIR / agent_name / "system_prompt.txt"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(output, encoding="utf-8")

    rel = out_path.relative_to(PROJECT_ROOT)
    print(f"Wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
